// Auto-generated by scripts/build-welcome-message.ts
// DO NOT EDIT - Edit scripts/build-welcome-message.ts instead

/**
 * Welcome message for Guest Chat - Multi-tenant version
 *
 * - WELCOME_MESSAGE_RAW: Original markdown string (for editing, testing)
 * - WELCOME_MESSAGE_HTML: Pre-rendered HTML (for optimal LCP)
 * - getWelcomeMessageHTML(): Dynamic function for multi-tenant branding
 *
 * To update:
 * 1. Edit WELCOME_MESSAGE in scripts/build-welcome-message.ts
 * 2. Run: npm run build (or tsx scripts/build-welcome-message.ts)
 * 3. Commit both script + generated file
 */

/**
 * Generate dynamic welcome message HTML with tenant name
 * @param tenantName - Name of the tenant/business
 * @returns HTML string for welcome message
 */
export function getWelcomeMessageHTML(tenantName: string): string {
  return `<p><strong class="font-semibold text-gray-900">¡Hola! Bienvenido a ${tenantName}</strong> 🌴</p>
<p>Estoy aquí para ayudarte a encontrar tu alojamiento perfecto en San Andrés.</p>
<p>Para mostrarte las mejores opciones rápidamente, cuéntame tu <strong class="font-semibold text-gray-900">fecha de llegada</strong> y <strong class="font-semibold text-gray-900">fecha de salida</strong>. ¿Vienes solo, en pareja o con más personas?</p>
<hr class="my-3 border-gray-300"/>
<p>🗨️ TIP: Puedes hablar conmigo en el idioma que prefieras 🗺️</p>`
}

// Legacy exports for backward compatibility (deprecated - use getWelcomeMessageHTML instead)
export const WELCOME_MESSAGE_RAW = "**¡Hola! Bienvenido a Simmer Down** 🌴\n\nEstoy aquí para ayudarte a encontrar tu alojamiento perfecto en San Andrés.\n\nPara mostrarte las mejores opciones rápidamente, cuéntame tu **fecha de llegada** y **fecha de salida**. ¿Vienes solo, en pareja o con más personas?\n\n---\n\n🗨️ TIP: Puedes hablar conmigo en el idioma que prefieras 🗺️"

export const WELCOME_MESSAGE_HTML = getWelcomeMessageHTML('Simmer Down') // Fallback for legacy code
